Import('env')
list = Split("""metaconsist.tex
                metaconsist.bib
                figures/mcfigure1.eps
                figures/mcfigure2.eps
                figures/mcfigure3.eps""")
env.DVI(list)

