Import('env')
list = Split("""archconsist.tex
                abstract.tex
                authors.tex
                keywords.tex
                title.tex
                archconsist.bib
                figures/figure1.eps
                figures/figure2.eps
                figures/figure3.eps
                figures/figure4.eps""")
env.DVI(list)

